### ISSUE TITLE
Could you provide some help getting this running?

### ISSUE THREAD

**Issue by cjustinhall** [koush/myq#1]
I'm getting many errors when I try to build. Here's my process...

git clone https://github.com/koush/myq.git myq-v6
cd myq-v6
npm install

then when I run 'npm run prepublishOnly' or 'npm run watch' I get many errors...

/home/bbb/nodeapps/myq-v6/src/myq-api.ts
    7:1   warning  Imports should be sorted alphabetically                 sort-imports
   84:5   error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
   84:20  error    Unsafe construction of an any type value                @typescript-eslint/no-unsafe-call
   89:5   error    Unsafe member access .set on an `any` value             @typescript-eslint/no-unsafe-member-access
   89:5   error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  116:11  error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  126:5   error    Unsafe return of an `any` typed value                   @typescript-eslint/no-unsafe-return
  133:39  error    Unsafe member access ["set-cookie"] on an `any` value   @typescript-eslint/no-unsafe-member-access
  133:39  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  133:39  error    Unsafe member access .headers on an `any` value         @typescript-eslint/no-unsafe-member-access
  136:11  error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  136:28  error    Unsafe member access .text on an `any` value            @typescript-eslint/no-unsafe-member-access
  136:28  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  137:11  error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  137:27  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  138:38  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  138:38  error    Unsafe member access .querySelector on an `any` value   @typescript-eslint/no-unsafe-member-access
  138:38  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  138:38  error    Unsafe member access .getAttribute on an `any` value    @typescript-eslint/no-unsafe-member-access
  149:11  error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  149:39  error    Unsafe member access .url on an `any` value             @typescript-eslint/no-unsafe-member-access
  167:8   error    Unsafe member access .headers on an `any` value         @typescript-eslint/no-unsafe-member-access
  167:8   error    Unsafe member access ["set-cookie"] on an `any` value   @typescript-eslint/no-unsafe-member-access
  167:8   error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  172:5   error    Unsafe return of an `any` typed value                   @typescript-eslint/no-unsafe-return
  179:25  error    Unsafe member access .headers on an `any` value         @typescript-eslint/no-unsafe-member-access
  179:25  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  183:39  error    Unsafe member access ["set-cookie"] on an `any` value   @typescript-eslint/no-unsafe-member-access
  183:39  error    Unsafe member access .headers on an `any` value         @typescript-eslint/no-unsafe-member-access
  183:39  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  186:11  error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  199:5   error    Unsafe return of an `any` typed value                   @typescript-eslint/no-unsafe-return
  206:11  error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  206:18  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  209:9   error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  209:48  error    Unsafe member access .code_challenge on an `any` value  @typescript-eslint/no-unsafe-member-access
  216:5   error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  223:5   error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  230:33  error    Unsafe member access .headers on an `any` value         @typescript-eslint/no-unsafe-member-access
  230:33  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  235:7   error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  235:24  error    Unsafe member access .toString on an `any` value        @typescript-eslint/no-unsafe-member-access
  235:24  error    Unsafe member access .from on an `any` value            @typescript-eslint/no-unsafe-member-access
  235:24  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  235:24  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  237:7   error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  237:24  error    Unsafe member access .code_verifier on an `any` value   @typescript-eslint/no-unsafe-member-access
  245:5   error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  260:25  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  260:25  error    Unsafe member access .json on an `any` value            @typescript-eslint/no-unsafe-member-access
  300:5   error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  300:5   error    Unsafe member access .set on an `any` value             @typescript-eslint/no-unsafe-member-access
  377:13  error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  389:26  error    Unsafe member access .json on an `any` value            @typescript-eslint/no-unsafe-member-access
  389:26  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  391:18  error    Unsafe member access .inspect on an `any` value         @typescript-eslint/no-unsafe-member-access
  391:18  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  449:7   error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  454:7   error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  474:11  error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  482:24  error    Unsafe member access .json on an `any` value            @typescript-eslint/no-unsafe-member-access
  482:24  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  484:16  error    Unsafe member access .inspect on an `any` value         @typescript-eslint/no-unsafe-member-access
  484:16  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  586:7   error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  586:7   error    Unsafe member access .headers on an `any` value         @typescript-eslint/no-unsafe-member-access
  590:7   error    Unsafe assignment of an `any` value                     @typescript-eslint/no-unsafe-assignment
  590:24  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  593:10  error    Unsafe member access .status on an `any` value          @typescript-eslint/no-unsafe-member-access
  600:11  error    Unsafe member access .ok on an `any` value              @typescript-eslint/no-unsafe-member-access
  600:27  error    Unsafe call of an `any` typed value                     @typescript-eslint/no-unsafe-call
  600:38  error    Unsafe member access .status on an `any` value          @typescript-eslint/no-unsafe-member-access
  602:57  error    Unsafe member access .status on an `any` value          @typescript-eslint/no-unsafe-member-access
  602:74  error    Unsafe member access .statusText on an `any` value      @typescript-eslint/no-unsafe-member-access
  606:7   error    Unsafe return of an `any` typed value                   @typescript-eslint/no-unsafe-return

? 75 problems (74 errors, 1 warning)

[bbb@bbb myq-v6]$ npm run watch

> @koush/myq@1.0.1 watch
> npm run build && npm link && nodemon

> @koush/myq@1.0.1 build
> rimraf ./dist && tsc

src/myq-api.ts:5:92 - error TS2307: Cannot find module 'node-fetch' or its corresponding type declarations.

5 import fetch, { FetchError, Headers, RequestInfo, RequestInit, Response, isRedirect } from "node-fetch";
                                                                                             ~~~~~~~~~~~~

src/myq-api.ts:9:23 - error TS2307: Cannot find module 'node-html-parser' or its corresponding type declarations.

9 import { parse } from "node-html-parser";
                        ~~~~~~~~~~~~~~~~~~

src/myq-api.ts:10:27 - error TS2307: Cannot find module 'pkce-challenge' or its corresponding type declarations.

10 import pkceChallenge from "pkce-challenge";
                             ~~~~~~~~~~~~~~~~

src/myq-api.ts:11:18 - error TS2307: Cannot find module 'util' or its corresponding type declarations.

11 import util from "util";
                    ~~~~~~

src/myq-api.ts:235:24 - error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

235       "client_secret": Buffer.from(MYQ_API_CLIENT_SECRET, "base64").toString(),
                           ~~~~~~

src/myq-api.ts:612:16 - error TS2571: Object is of type 'unknown'.

612         switch(error.code) {
                   ~~~~~

src/myq-api.ts:631:28 - error TS2571: Object is of type 'unknown'.

631             this.log.error(error.message);
                               ~~~~~


Found 7 errors.



Any help/tips/suggestions to getting this built? Thanks

**Comment by koush** [comment]
npm install
npm run build

That's all it should be

**Comment by koush** [comment]
was missing some dependencies

https://github.com/koush/myq/commit/1299fcfff5ef132764c054e062f121645f7acaa9

**Comment by cjustinhall** [comment]
pulled a clean version of the package.json and redid the install/build - built cleanly! Thx. On to next step :)

**Comment by cjustinhall** [comment]
Just curious before I start digging in, do you have a sample js that will use this api to login to myq and show all devices?

**Comment by koush** [comment]
https://github.com/hjdhjd/homebridge-myq
