### ISSUE TITLE
Are you planning to support this package long-term?

### ISSUE THREAD

**Issue by txase** [koush/myq#2]
I've been a user of the [myq-api package](https://github.com/thomasmunduchira/myq-api). Unfortunately, that package [hasn't been updated for v6 yet](https://github.com/thomasmunduchira/myq-api/issues/34#issuecomment-907851701). Are you planning to maintain this long-term (possibly by syncing updates from homebridge)? Or is this a temporary solution for your own private purposes while we wait for projects like myq-api to receive v6 support?

**Comment by koush** [comment]
@hjdhjd ideally would take over as this is his code. I've also forked another homebridge project of his to extract the API bindings.

**Comment by koush** [comment]
The answer is as it always is for unpaid open source: no I don't plan to support this long term, only as long as it is needed by me.

**Comment by hjdhjd** [comment]
LOL. Another one @koush? :smile: Yeah, since there's interest here, I'll create a standalone package for my API implementation.

**Comment by koush** [comment]
> LOL. Another one @koush? 😄 Yeah, since there's interest here, I'll create a standalone package for my API implementation.

what can I say, you do great work!

**Comment by hjdhjd** [comment]
😊 Too kind.

**Comment by hjdhjd** [comment]
@txase See: https://github.com/hjdhjd/myq

@koush I’ve released my API implementation as a standalone library. It’s got a couple of improvements you might be interested in as well under the hood that streamline the experience from the version you forked here.

**Comment by txase** [comment]
@hjdhjd I just wanted to add two things to my emoji reactions above:

1. 🙏, as a soon-to-be-user of your package, I’m very appreciative of your efforts. 
2. I cursorily reviewed your implementation, and it is stellar. Great usage of appropriate libs and the latest ES techniques. I would be very proud of the implementation if I had done it myself. Great work!
